"""empty message

Revision ID: 03e04d5d54ab
Revises: 
Create Date: 2020-07-15 23:28:36.419990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e04d5d54ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_item'), 'item', ['item'], unique=True)
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('listitem', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_listitem'), 'list', ['listitem'], unique=True)
    op.create_index(op.f('ix_list_username'), 'list', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_username'), table_name='list')
    op.drop_index(op.f('ix_list_listitem'), table_name='list')
    op.drop_table('list')
    op.drop_index(op.f('ix_item_item'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
