"""empty message

Revision ID: 85579611b1bc
Revises: a710c6dff45f
Create Date: 2020-07-16 12:26:34.923379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85579611b1bc'
down_revision = 'a710c6dff45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_userid', table_name='user')
    op.create_index(op.f('ix_user_userid'), 'user', ['userid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_userid'), table_name='user')
    op.create_index('ix_user_userid', 'user', ['userid'], unique=False)
    # ### end Alembic commands ###
